# Generated by Django 4.1 on 2022-09-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phonenumber', models.CharField(max_length=16, unique=True, verbose_name='手机号')),
                ('user_img', models.ImageField(default='default.jpg', upload_to='head_image/%Y/%m', verbose_name='用户头像')),
                ('user_password', models.CharField(max_length=24, verbose_name='登陆密码')),
                ('user_result', models.BooleanField(default=1, verbose_name='用户状态 True为允许登陆False为禁止登陆')),
                ('user_tc_password', models.CharField(max_length=6, verbose_name='6为交易密码')),
                ('user_name', models.CharField(max_length=12, verbose_name='用户名称')),
                ('user_vip', models.PositiveSmallIntegerField(default=0, verbose_name='会员VIP等级')),
                ('user_reg_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user_login_time', models.DateTimeField(verbose_name='登陆时间')),
                ('user_set_time', models.DateTimeField(auto_now=True, verbose_name='最后_更改时间')),
                ('user_ip', models.GenericIPAddressField(default='127.0.0.1', protocol='IPv4', verbose_name='用户注册ip地址')),
            ],
            options={
                'verbose_name': '会员用户信息',
                'verbose_name_plural': '会员用户信息',
                'db_table': 'user_conf',
            },
        ),
    ]
