# Generated by Django 4.1 on 2022-09-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconf',
            name='user_img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='head_image/%Y/%m', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='userconf',
            name='user_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', null=True, protocol='IPv4', verbose_name='用户注册ip地址'),
        ),
        migrations.AlterField(
            model_name='userconf',
            name='user_login_time',
            field=models.DateTimeField(null=True, verbose_name='登陆时间'),
        ),
        migrations.AlterField(
            model_name='userconf',
            name='user_name',
            field=models.CharField(default='', max_length=12, null=True, verbose_name='用户名称'),
        ),
        migrations.AlterField(
            model_name='userconf',
            name='user_reg_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='userconf',
            name='user_result',
            field=models.BooleanField(default=1, null=True, verbose_name='用户状态 True为允许登陆False为禁止登陆'),
        ),
        migrations.AlterField(
            model_name='userconf',
            name='user_set_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后_更改时间'),
        ),
        migrations.AlterField(
            model_name='userconf',
            name='user_vip',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='会员VIP等级'),
        ),
    ]
